blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/YuSabo90002/sphinxcontrib-typst/blob/main/README.md
    about: Check the documentation for usage instructions and examples
  - name: Discussions
    url: https://github.com/YuSabo90002/sphinxcontrib-typst/discussions
    about: Ask questions and discuss ideas with the community
