name: Feature Request
description: Suggest a new feature for typsphinx
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this feature needed? What problem does it solve?
      placeholder: |
        I'm working on a project where...
        Currently, I have to...
        This feature would allow me to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working? (Optional)
      placeholder: |
        - Add a new configuration option...
        - Implement a new directive...
        - Extend the translator to support...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you would use this feature (Optional)
      placeholder: |
        .. code-block:: rst

           .. your-new-directive::
              :option: value

              Content here...
      render: rst
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? (Optional)
      placeholder: |
        - Using a custom extension...
        - Manually editing the Typst output...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
          required: false
