name: Documentation

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync --extra docs
          uv pip install -e .

      - name: Build HTML documentation
        run: |
          cd docs
          uv run sphinx-build -b html source _build/html

      - name: Build PDF documentation
        run: |
          cd docs
          uv run sphinx-build -b typstpdf source _build/pdf

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-html
          path: docs/_build/html

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: docs/_build/pdf/*.pdf

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          cname: false

      - name: Upload PDF to Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: docs/_build/pdf/*.pdf
          draft: false
          prerelease: false
